/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;
/**
 *
 * @author Connor Polanka
 */
import Client.Threading;
import Client.client;
import Message.DirectMessage;
import User.UserProfile;
import java.util.*;
import java.text.*;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
String TempUserName;
//DirectMessage DM;
//UserProfile user;
client c = new client();
UserProfile User = new UserProfile();
//private String username;
private SimpleDateFormat ft = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
private Date date;



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        pnlNull = new javax.swing.JPanel();
        lblFriendFace = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        btnPostWall = new javax.swing.JButton();
        btnMessaging = new javax.swing.JButton();
        btnFriends = new javax.swing.JButton();
        btnGroupMessaging = new javax.swing.JButton();
        pnlVariable = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        userProfilePanel = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        btnDM = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cboxFriends = new javax.swing.JComboBox<>();
        lblFriendSelector = new javax.swing.JLabel();
        btnRefreshVP = new javax.swing.JButton();
        userProfileEditPanel = new javax.swing.JPanel();
        txtNameEdit = new javax.swing.JTextField();
        btnRevert = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        btnViewProfile1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblNameEdit = new javax.swing.JLabel();
        txtEmailEdit = new javax.swing.JTextField();
        lblEmailEdit = new javax.swing.JLabel();
        pnlFriends = new javax.swing.JPanel();
        lblFriends = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaFriends = new javax.swing.JTextArea();
        pnlDirectMessaging = new javax.swing.JPanel();
        comboRecipient = new javax.swing.JComboBox<>();
        lblRecipient = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        txtaDM = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRefreshDM = new javax.swing.JButton();
        pnlGroupMessage = new javax.swing.JPanel();
        lblGroupMessage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaGroupMessaging = new javax.swing.JTextArea();
        txtGroupMessage = new javax.swing.JTextField();
        lblGroupMessageWrite = new javax.swing.JLabel();
        btnGroupMessageSend = new javax.swing.JButton();
        btnAddFriend = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaGroup = new javax.swing.JTextArea();
        cboxAddFriend = new javax.swing.JComboBox<>();
        pnlPublicWall = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaWall = new javax.swing.JTextArea();
        btnPost = new javax.swing.JButton();
        txtPost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlControl.setLayout(new java.awt.CardLayout());

        pnlNull.setLayout(null);

        lblFriendFace.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblFriendFace.setText("FriendFace");
        pnlNull.add(lblFriendFace);
        lblFriendFace.setBounds(150, 10, 310, 70);

        pnlControl.add(pnlNull, "card3");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnEditProfile.setText("Edit Profile");
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });

        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        btnPostWall.setText("Post Wall");
        btnPostWall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostWallActionPerformed(evt);
            }
        });

        btnMessaging.setText("Direct Messaging");
        btnMessaging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessagingActionPerformed(evt);
            }
        });

        btnFriends.setText("Friends");
        btnFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriendsActionPerformed(evt);
            }
        });

        btnGroupMessaging.setText("Group Messaging");
        btnGroupMessaging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupMessagingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPostWall))
                .addGap(18, 18, 18)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMessaging)
                    .addComponent(btnEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGroupMessaging))
                    .addComponent(btnFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnEditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewProfile)
                    .addComponent(btnGroupMessaging))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPostWall)
                    .addComponent(btnMessaging)
                    .addComponent(btnFriends))
                .addContainerGap())
        );

        pnlControl.add(pnlMenu, "card5");

        getContentPane().add(pnlControl, java.awt.BorderLayout.PAGE_START);

        pnlVariable.setLayout(new java.awt.CardLayout());

        lblUser.setText("Username");

        lblPass.setText("Password");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnExit1.setText("Exit");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLogin.setText("Login");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/friend face logo.jpg"))); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnLogin))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPass, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(btnRegister)
                        .addGap(223, 223, 223)))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit1)
                .addContainerGap())
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(lblLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser))
                        .addGap(36, 36, 36)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegister)
                            .addComponent(btnLogin)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(btnExit1)
                .addContainerGap())
        );

        pnlVariable.add(loginPanel, "card5");

        txtName.setEditable(false);

        btnDM.setText("Message");
        btnDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("View Profile");

        lblName.setText("Name");

        lblEmail.setText("Email");

        txtEmail.setEditable(false);

        cboxFriends.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPolanka", "ABrown", "AOppenh", "LPerry", "DBurgos" }));

        lblFriendSelector.setText("Friend");

        btnRefreshVP.setText("Refresh");

        javax.swing.GroupLayout userProfilePanelLayout = new javax.swing.GroupLayout(userProfilePanel);
        userProfilePanel.setLayout(userProfilePanelLayout);
        userProfilePanelLayout.setHorizontalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userProfilePanelLayout.createSequentialGroup()
                .addContainerGap(417, Short.MAX_VALUE)
                .addComponent(btnDM)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userProfilePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addComponent(lblFriendSelector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRefreshVP))
                .addGap(60, 60, 60))
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userProfilePanelLayout.setVerticalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(cboxFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFriendSelector))
                .addGap(41, 41, 41)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshVP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btnDM)
                .addGap(41, 41, 41))
        );

        pnlVariable.add(userProfilePanel, "card3");

        btnRevert.setText("Revert");

        btnSaveChanges.setText("Save Changes");

        btnViewProfile1.setText("View Profile");
        btnViewProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfile1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Edit Profile");

        lblNameEdit.setText("Name");

        lblEmailEdit.setText("Email");

        javax.swing.GroupLayout userProfileEditPanelLayout = new javax.swing.GroupLayout(userProfileEditPanel);
        userProfileEditPanel.setLayout(userProfileEditPanelLayout);
        userProfileEditPanelLayout.setHorizontalGroup(
            userProfileEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfileEditPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(userProfileEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNameEdit)
                    .addComponent(lblEmailEdit))
                .addGap(18, 18, 18)
                .addGroup(userProfileEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmailEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(txtNameEdit))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(userProfileEditPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(userProfileEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userProfileEditPanelLayout.createSequentialGroup()
                        .addComponent(btnRevert)
                        .addGap(98, 98, 98)
                        .addComponent(btnSaveChanges))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnViewProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        userProfileEditPanelLayout.setVerticalGroup(
            userProfileEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfileEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(userProfileEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameEdit))
                .addGap(18, 18, 18)
                .addGroup(userProfileEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(userProfileEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRevert)
                    .addComponent(btnSaveChanges)
                    .addComponent(btnViewProfile1))
                .addGap(55, 55, 55))
        );

        pnlVariable.add(userProfileEditPanel, "card2");

        lblFriends.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFriends.setText("Friends");

        txtaFriends.setEditable(false);
        txtaFriends.setColumns(20);
        txtaFriends.setRows(5);
        jScrollPane2.setViewportView(txtaFriends);

        javax.swing.GroupLayout pnlFriendsLayout = new javax.swing.GroupLayout(pnlFriends);
        pnlFriends.setLayout(pnlFriendsLayout);
        pnlFriendsLayout.setHorizontalGroup(
            pnlFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFriendsLayout.createSequentialGroup()
                .addGroup(pnlFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFriendsLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFriendsLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblFriends)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        pnlFriendsLayout.setVerticalGroup(
            pnlFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFriendsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblFriends)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVariable.add(pnlFriends, "card7");

        comboRecipient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPolanka", "ABrown", "AOppenh", "LPerry", "DBurgos" }));
        comboRecipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRecipientActionPerformed(evt);
            }
        });

        lblRecipient.setText("Recipient");

        txtaDM.setEditable(false);
        txtaDM.setColumns(20);
        txtaDM.setRows(5);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblMessage.setText("Message");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Direct Messaging");

        btnRefreshDM.setText("Refresh");

        javax.swing.GroupLayout pnlDirectMessagingLayout = new javax.swing.GroupLayout(pnlDirectMessaging);
        pnlDirectMessaging.setLayout(pnlDirectMessagingLayout);
        pnlDirectMessagingLayout.setHorizontalGroup(
            pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                .addGroup(pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecipient)
                            .addComponent(lblMessage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnSend))
                            .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                                .addComponent(comboRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                .addComponent(btnRefreshDM))))
                    .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel3)))
                .addGap(107, 107, 107))
            .addGroup(pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                    .addGap(0, 104, Short.MAX_VALUE)
                    .addComponent(txtaDM, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 103, Short.MAX_VALUE)))
        );
        pnlDirectMessagingLayout.setVerticalGroup(
            pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecipient))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addGroup(pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSend)
                            .addComponent(lblMessage))
                        .addGap(45, 45, 45))
                    .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnRefreshDM)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlDirectMessagingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDirectMessagingLayout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(txtaDM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 124, Short.MAX_VALUE)))
        );

        pnlVariable.add(pnlDirectMessaging, "card4");

        lblGroupMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGroupMessage.setText("Group Messaging");

        txtaGroupMessaging.setEditable(false);
        txtaGroupMessaging.setColumns(20);
        txtaGroupMessaging.setRows(5);
        jScrollPane3.setViewportView(txtaGroupMessaging);

        lblGroupMessageWrite.setText("Message");

        btnGroupMessageSend.setText("Send");
        btnGroupMessageSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupMessageSendActionPerformed(evt);
            }
        });

        btnAddFriend.setText("Add");
        btnAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFriendActionPerformed(evt);
            }
        });

        txtaGroup.setEditable(false);
        txtaGroup.setColumns(20);
        txtaGroup.setRows(5);
        jScrollPane4.setViewportView(txtaGroup);

        cboxAddFriend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPolanka", "ABrown", "AOppenh", "LPerry", "DBurgos" }));

        javax.swing.GroupLayout pnlGroupMessageLayout = new javax.swing.GroupLayout(pnlGroupMessage);
        pnlGroupMessage.setLayout(pnlGroupMessageLayout);
        pnlGroupMessageLayout.setHorizontalGroup(
            pnlGroupMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGroupMessageLayout.createSequentialGroup()
                .addGroup(pnlGroupMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGroupMessageLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlGroupMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGroupMessageLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlGroupMessageLayout.createSequentialGroup()
                                .addComponent(lblGroupMessageWrite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGroupMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnGroupMessageSend))))
                    .addGroup(pnlGroupMessageLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(pnlGroupMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlGroupMessageLayout.createSequentialGroup()
                                .addComponent(cboxAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddFriend))
                            .addComponent(lblGroupMessage))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlGroupMessageLayout.setVerticalGroup(
            pnlGroupMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGroupMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGroupMessage)
                .addGap(30, 30, 30)
                .addGroup(pnlGroupMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFriend)
                    .addComponent(cboxAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlGroupMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlGroupMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGroupMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGroupMessageWrite)
                    .addComponent(btnGroupMessageSend))
                .addGap(35, 35, 35))
        );

        pnlVariable.add(pnlGroupMessage, "card8");

        txtaWall.setEditable(false);
        txtaWall.setColumns(20);
        txtaWall.setRows(5);
        jScrollPane1.setViewportView(txtaWall);

        btnPost.setText("Post");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });

        jLabel1.setText("Make a post!");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Post Wall");

        javax.swing.GroupLayout pnlPublicWallLayout = new javax.swing.GroupLayout(pnlPublicWall);
        pnlPublicWall.setLayout(pnlPublicWallLayout);
        pnlPublicWallLayout.setHorizontalGroup(
            pnlPublicWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPublicWallLayout.createSequentialGroup()
                .addGroup(pnlPublicWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPublicWallLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPublicWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPost, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)))
                    .addGroup(pnlPublicWallLayout.createSequentialGroup()
                        .addGroup(pnlPublicWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPublicWallLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnPost))
                            .addGroup(pnlPublicWallLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlPublicWallLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPublicWallLayout.setVerticalGroup(
            pnlPublicWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPublicWallLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(txtPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPost)
                .addGap(56, 56, 56))
        );

        pnlVariable.add(pnlPublicWall, "card6");

        getContentPane().add(pnlVariable, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    

    
  
    private void startInfo(){ //Gathers and sets info for other classes
        
    }
    
    

    
    
    
    
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //Exit
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
        //navigate to Edit Profile
        pnlVariable.removeAll();
        pnlVariable.add(userProfileEditPanel);
        pnlVariable.repaint();
        pnlVariable.revalidate();
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // Navigate to View Profile
        pnlVariable.removeAll();
        pnlVariable.add(userProfilePanel);
        pnlVariable.repaint();
        pnlVariable.revalidate();

    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //pull user and pass
        c.startSocket();
        
        
        
//        User.setUsername(txtUser.getText());
//        DM.setSenderName(User.getUsername());
        User.setUsername(txtUser.getText());
        //username = txtUser.getText();
        String user = txtUser.getText();
        String pass = txtPass.getText();
        //send user and pass to server
        //check if valid
        c.send("LG|" + user + "|"+ c.hash(pass));
        //if successful, server will send "SUCCESS"
        //success changes approved to true
       //if(approved.equals(true))
        //{
       /* pnlVariable.removeAll();
        pnlVariable.add(pnlPublicWall);
        pnlVariable.repaint();
        pnlVariable.revalidate();
        
        pnlControl.removeAll();
        pnlControl.add(pnlMenu);
        pnlControl.repaint();
        pnlControl.revalidate();*/
        //}
        
        
     
        
    }//GEN-LAST:event_btnLoginActionPerformed

    public static void login() {
        pnlVariable.removeAll();
        pnlVariable.add(pnlPublicWall);
        pnlVariable.repaint();
        pnlVariable.revalidate();

        pnlControl.removeAll();
        pnlControl.add(pnlMenu);
        pnlControl.repaint();
        pnlControl.revalidate();
    }

    public static void dm(String str) {
        txtaDM.setText(txtaDM.getText()+"\n"+str);
    }

    public static void gm(String str) {
        txtaGroupMessaging.setText(txtaGroupMessaging.getText()+"\n"+str);
    }

    public static void pt(String str) {
        txtaWall.setText(txtaWall.getText()+"\n"+str);
    }

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // Exit
        System.exit(0);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnPostWallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostWallActionPerformed
        
        pnlVariable.removeAll();
        pnlVariable.add(pnlPublicWall);
        pnlVariable.repaint();
        pnlVariable.revalidate();
    }//GEN-LAST:event_btnPostWallActionPerformed

    private void btnDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMActionPerformed
        
        pnlVariable.removeAll();
        pnlVariable.add(pnlDirectMessaging);
        pnlVariable.repaint();
        pnlVariable.revalidate();
    }//GEN-LAST:event_btnDMActionPerformed

    private void comboRecipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRecipientActionPerformed
        //add arraylist of profile names or IDs
    }//GEN-LAST:event_comboRecipientActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        //pull from txtMessage
        //DM.setSendee(); Needs to pull sendee from selected friend list
       // DM.setMessage(txtMessage.getText());
        String DM = txtMessage.getText();
        date = new Date();
        //Send it
       c.send("DM|" + User.getUsername() + "|" + comboRecipient.getSelectedItem().toString() + "|" + ft.format(date) + " - " + txtMessage.getText());
        
        
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnViewProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfile1ActionPerformed
        
        
        pnlVariable.removeAll();
        pnlVariable.add(userProfilePanel);
        pnlVariable.repaint();
        pnlVariable.revalidate();
    }//GEN-LAST:event_btnViewProfile1ActionPerformed

    private void btnMessagingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessagingActionPerformed
        pnlVariable.removeAll();
        pnlVariable.add(pnlDirectMessaging);
        pnlVariable.repaint();
        pnlVariable.revalidate();
    }//GEN-LAST:event_btnMessagingActionPerformed

    private void btnFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriendsActionPerformed
        
        pnlVariable.removeAll();
        pnlVariable.add(pnlFriends);
        pnlVariable.repaint();
        pnlVariable.revalidate();
        
    }//GEN-LAST:event_btnFriendsActionPerformed

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        //store post
        String post = txtPost.getText();

        date = new Date();
        
        //clear post
        txtPost.setText("");
        //put post on wall
        String WallPost = ("PT|" + ft.format(date) + " - " + User.getUsername() + ":  " + post);
        //txtaWall.append(WallPost); 
        //send to server
        
        
        c.send(WallPost);
        //out.println("GPT:"+ TempUserName);
        
        
        
        
    }//GEN-LAST:event_btnPostActionPerformed

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        //add cbox person to txtaGroup
        //send person to server
        txtaGroup.append(cboxAddFriend.getSelectedItem().toString()+"\n");
        
    }//GEN-LAST:event_btnAddFriendActionPerformed

    private void btnGroupMessageSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupMessageSendActionPerformed
        if (!txtGroupMessage.getText().equals("")) {
            date = new Date();
            //send message to server
            c.send("GM|" + User.getUsername() + "|" + txtaGroup.getText().replaceAll("\n", "|") + ft.format(date) + " - " + User.getUsername() + ":  " + txtGroupMessage.getText());
        }

        //clear box
        txtGroupMessage.setText("");
    }//GEN-LAST:event_btnGroupMessageSendActionPerformed

    private void btnGroupMessagingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupMessagingActionPerformed
        pnlVariable.removeAll();
        pnlVariable.add(pnlGroupMessage);
        pnlVariable.repaint();
        pnlVariable.revalidate();
                
                
                
    }//GEN-LAST:event_btnGroupMessagingActionPerformed



    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {
        c.startSocket();
        //grab name and user
        String user = txtUser.getText();
        String pass = txtPass.getText();
        //send to server
        c.send("RG|" + user + "|"+ c.hash(pass));
    }

    ArrayList<String> usernames = new ArrayList<String>(
            Arrays.asList("CPolanka", "ABrown", "AOppenh", "LPerry", "DBurgos"));

    ArrayList<String> names = new ArrayList<String>(
            Arrays.asList("Connor Polanka", "Asa Brown", "Andrew Oppenheimer", "Landan Perry", "David Burgos"));

    ArrayList<String> emails = new ArrayList<String>(
            Arrays.asList("CPolanka@purdue.edu", "ABrown@purdue.edu", "AOppenh@purdue.edu", "LPerry@purdue.edu", "DBurgos@purdue.edu"));




    private void btnRefreshVPActionPerformed(java.awt.event.ActionEvent evt) {
        // take the selected user from cbox
        String currentFriend = cboxFriends.getName();
        //Find profile associated with username

        //save in variable
        String tempName = names.get(usernames.indexOf(currentFriend));
        String tempEmail = emails.get(usernames.indexOf(currentFriend));
        //display their info


        txtName.setText(tempName);
        txtEmail.setText(tempEmail);


    }


    private void btnRevertActionPerformed(java.awt.event.ActionEvent evt) {
        // pull original login

        //compare to the arraylists

        // pull name and email




        //save in variable
        String tempName = names.get(usernames.indexOf("AOppenh"));
        String tempEmail = emails.get(usernames.indexOf("AOppenh"));
        //display their info


        txtNameEdit.setText(tempName);
        txtEmailEdit.setText(tempEmail);


    }

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {
        //pull from field
        String tempNE = txtNameEdit.getText();
        String tempEE = txtEmailEdit.getText();

        names.set(usernames.indexOf("AOppenh"), tempNE);
        emails.set(usernames.indexOf("AOppenh"), tempEE);








    }





//    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {
//        //add cbox person to txtaGroup
//        txtaGroup.append(cboxAddFriend.getSelectedItem().toString());
//
//
//
//    }

//    private void btnGroupMessageSendActionPerformed(java.awt.event.ActionEvent evt) {
//        //send message to server
//        c.send("GM|" + "TODO" + txtaGroup.getText() + txtGroupMessage.getText());
//        //clear box
//        txtGroupMessage.setText("");
//    }

























    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnAddFriend;
    private static javax.swing.JButton btnDM;
    private static javax.swing.JButton btnEditProfile;
    private static javax.swing.JButton btnExit;
    private static javax.swing.JButton btnExit1;
    private static javax.swing.JButton btnFriends;
    private static javax.swing.JButton btnGroupMessageSend;
    private static javax.swing.JButton btnGroupMessaging;
    private static javax.swing.JButton btnLogin;
    private static javax.swing.JButton btnMessaging;
    private static javax.swing.JButton btnPost;
    private static javax.swing.JButton btnPostWall;
    private static javax.swing.JButton btnRefreshDM;
    private static javax.swing.JButton btnRefreshVP;
    private static javax.swing.JButton btnRegister;
    private static javax.swing.JButton btnRevert;
    private static javax.swing.JButton btnSaveChanges;
    private static javax.swing.JButton btnSend;
    private static javax.swing.JButton btnViewProfile;
    private static javax.swing.JButton btnViewProfile1;
    private static javax.swing.JComboBox<String> cboxAddFriend;
    private static javax.swing.JComboBox<String> cboxFriends;
    private static javax.swing.JComboBox<String> comboRecipient;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel8;
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JScrollPane jScrollPane4;
    private static javax.swing.JLabel lblEmail;
    private static javax.swing.JLabel lblEmailEdit;
    private static javax.swing.JLabel lblFriendFace;
    private static javax.swing.JLabel lblFriendSelector;
    private static javax.swing.JLabel lblFriends;
    private static javax.swing.JLabel lblGroupMessage;
    private static javax.swing.JLabel lblGroupMessageWrite;
    private static javax.swing.JLabel lblLogin;
    private static javax.swing.JLabel lblMessage;
    private static javax.swing.JLabel lblName;
    private static javax.swing.JLabel lblNameEdit;
    private static javax.swing.JLabel lblPass;
    private static javax.swing.JLabel lblRecipient;
    private static javax.swing.JLabel lblUser;
    private static javax.swing.JPanel loginPanel;
    private static javax.swing.JPanel pnlControl;
    private static javax.swing.JPanel pnlDirectMessaging;
    private static javax.swing.JPanel pnlFriends;
    private static javax.swing.JPanel pnlGroupMessage;
    private static javax.swing.JPanel pnlMenu;
    private static javax.swing.JPanel pnlNull;
    private static javax.swing.JPanel pnlPublicWall;
    private static javax.swing.JPanel pnlVariable;
    private static javax.swing.JTextField txtEmail;
    private static javax.swing.JTextField txtEmailEdit;
    private static javax.swing.JTextField txtGroupMessage;
    private static javax.swing.JTextField txtMessage;
    private static javax.swing.JTextField txtName;
    private static javax.swing.JTextField txtNameEdit;
    private static javax.swing.JPasswordField txtPass;
    private static javax.swing.JTextField txtPost;
    private static javax.swing.JTextField txtUser;
    private static javax.swing.JTextArea txtaDM;
    private static javax.swing.JTextArea txtaFriends;
    private static javax.swing.JTextArea txtaGroup;
    private static javax.swing.JTextArea txtaGroupMessaging;
    private static javax.swing.JTextArea txtaWall;
    private static javax.swing.JPanel userProfileEditPanel;
    private static javax.swing.JPanel userProfilePanel;
    // End of variables declaration//GEN-END:variables
}
